name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Workflow dispatch' 
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to atndr.net registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: pashutk/atndr:latest
